import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { gameInfo, qwikRefData, penalties, crewEmails } = await request.json();
    
    const emailSubject = `QwikRef Report: ${gameInfo.homeTeam} vs ${gameInfo.awayTeam} - ${gameInfo.date}`;
    
    const emailBody = `
      <h2>RMAC Officials QwikRef Report</h2>
      <h3>Game Information</h3>
      <ul>
        <li><strong>Teams:</strong> ${gameInfo.homeTeam} vs ${gameInfo.awayTeam}</li>
        <li><strong>Date:</strong> ${gameInfo.date}</li>
        <li><strong>Crew:</strong> ${gameInfo.crew}</li>
        <li><strong>Total Penalties:</strong> ${penalties.length}</li>
      </ul>
      
      <h3>QwikRef Format</h3>
      <pre style="background: #f5f5f5; padding: 10px; border-radius: 5px;">
${qwikRefData}
      </pre>
      
      <h3>Detailed Penalty Summary</h3>
      <table border="1" style="border-collapse: collapse; width: 100%;">
        <tr>
          <th>Time</th>
          <th>Penalty</th>
          <th>Player</th>
          <th>Team</th>
          <th>Official</th>
          <th>Yards</th>
        </tr>
        ${penalties.map(p => `
          <tr>
            <td>${p.quarter} ${p.time}</td>
            <td>${p.code} - ${p.name}</td>
            <td>#${p.player}</td>
            <td>${p.team === 'O' ? 'Offense' : 'Defense'}</td>
            <td>${p.callingOfficial}</td>
            <td>${p.yards}</td>
          </tr>
        `).join('')}
      </table>
      
      <p><em>Generated by RMAC Officials Assistant</em></p>
    `;

    // Send email to crew members (implement with your email service)
    const emailResults = await Promise.all(
      crewEmails.map(async (email: string) => {
        // This would integrate with your actual email service
        // For now, we'll simulate success
        return { email, success: true };
      })
    );

    const successfulEmails = emailResults.filter(result => result.success);
    
    return NextResponse.json({
      success: true,
      recipientCount: successfulEmails.length,
      message: 'QwikRef report emailed successfully'
    });
    
  } catch (error) {
    console.error('Email error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to send email report' },
      { status: 500 }
    );
  }
}
